05/08/2022 00:29:07|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
05/08/2022 00:51:40|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
05/08/2022 03:22:40|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /movie?query=French+Kiss&year=1995 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1410c3fe80>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
05/08/2022 03:22:59|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /movie?query=French+Kiss&year=1995 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f140f0acd30>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
05/08/2022 03:23:18|INFO    |root                            |Throttling sucha for 1 hour, until 22/08/05 04:23, because of: ConnectTimeout. Exception info: MaxRetryError("HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /movie?query=French+Kiss&year=1995 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f140ee4ab20>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)'))")|
05/08/2022 03:23:18|INFO    |root                            |BAZARR Finished searching for Subtitles to upgrade. Check History for more information.|
05/08/2022 03:29:07|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
05/08/2022 03:51:40|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
05/08/2022 04:00:01|INFO    |root                            |BAZARR All existing episode subtitles indexed from disk.|
05/08/2022 05:00:00|INFO    |root                            |BAZARR All existing movie subtitles indexed from disk.|
05/08/2022 06:15:38|INFO    |root                            |Using sucha again after 1 hour, (disabled because: ConnectTimeout)|
05/08/2022 06:29:07|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
05/08/2022 06:51:40|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
05/08/2022 09:29:07|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
05/08/2022 09:51:40|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
05/08/2022 11:06:32|INFO    |root                            |BAZARR Running cache maintenance|
05/08/2022 12:29:07|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
05/08/2022 12:51:40|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
05/08/2022 15:22:35|WARNING |retry.api                       |HTTPSConnectionPool(host='argenteam.net', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
05/08/2022 15:22:40|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /movie?query=French+Kiss&year=1995 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1410e6b1c0>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
05/08/2022 15:22:45|WARNING |retry.api                       |HTTPSConnectionPool(host='www.subdivx.com', port=443): Read timed out. (read timeout=20), retrying in 5 seconds...|
05/08/2022 15:22:59|WARNING |retry.api                       |HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /movie?query=French+Kiss&year=1995 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f140f473a30>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)')), retrying in 5 seconds...|
05/08/2022 15:23:18|INFO    |root                            |Throttling sucha for 1 hour, until 22/08/05 16:23, because of: ConnectTimeout. Exception info: MaxRetryError("HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /movie?query=French+Kiss&year=1995 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f14191dd520>, 'Connection to sapidb.caretas.club timed out. (connect timeout=10)'))")|
05/08/2022 15:23:18|INFO    |root                            |BAZARR Finished searching for Subtitles to upgrade. Check History for more information.|
05/08/2022 15:29:07|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
05/08/2022 15:51:40|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
05/08/2022 18:25:09|ERROR   |root                            |Error trying to get releases from Github. Connection Error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 174, in _new_conn\n    conn = connection.create_connection(\n  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/http.py", line 325, in patched_create_connection\n    return _orig_create_connection(address, *args, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 72, in create_connection\n    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):\n  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\nsocket.gaierror: [Errno -3] Try again\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 703, in urlopen\n    httplib_response = self._make_request(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 386, in _make_request\n    self._validate_conn(conn)\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 1040, in _validate_conn\n    conn.connect()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 358, in connect\n    conn = self._new_conn()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 186, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f140f31f850>: Failed to establish a new connection: [Errno -3] Try again\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 440, in send\n    resp = conn.urlopen(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 785, in urlopen\n    retries = retries.increment(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/retry.py", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\'api.github.com\', port=443): Max retries exceeded with url: /repos/morpheus65535/Bazarr/releases?per_page=100 (Caused by NewConnectionError(\'<urllib3.connection.HTTPSConnection object at 0x7f140f31f850>: Failed to establish a new connection: [Errno -3] Try again\'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 22, in check_releases\n    r = requests.get(url_releases, allow_redirects=True)\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 75, in get\n    return request(\'get\', url, params=params, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 529, in request\n    resp = self.send(prep, **send_kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 645, in send\n    r = adapter.send(request, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 519, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPSConnectionPool(host=\'api.github.com\', port=443): Max retries exceeded with url: /repos/morpheus65535/Bazarr/releases?per_page=100 (Caused by NewConnectionError(\'<urllib3.connection.HTTPSConnection object at 0x7f140f31f850>: Failed to establish a new connection: [Errno -3] Try again\'))'|
05/08/2022 18:29:07|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
05/08/2022 18:51:40|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
05/08/2022 19:35:49|INFO    |root                            |Using sucha again after 1 hour, (disabled because: ConnectTimeout)|
05/08/2022 21:29:07|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
05/08/2022 21:51:40|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
